export const currencyAndSymbol = [
  {
    CountryName: 'Euro Member Countries',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
    Presented: true,
  },
  {
    CountryName: 'US Dollar',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
    Presented: true,
  },
  {
    CountryName: 'Central African CFA Franc BEAC',
    ISOCode: 'XAF',
    Currency: 'Central African CFA Franc BEAC',
    Symbol: 'FCFA',
    Presented: true,
  },
  {
    CountryName: 'Afghanistan',
    ISOCode: 'AFN',
    Currency: 'Afghan afghani',
    Symbol: '؋',
  },
  {
    CountryName: 'Albania',
    ISOCode: 'ALL',
    Currency: 'Albanian lek',
    Symbol: 'Lek',
  },
  {
    CountryName: 'Algeria',
    ISOCode: 'DZD',
    Currency: 'Algerian dinar',
    Symbol: 'دج',
  },
  {
    CountryName: 'Andorra',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Angola',
    ISOCode: 'AOA',
    Currency: 'Angolan kwanza',
    Symbol: 'Kz',
  },
  {
    CountryName: 'Antigua and Barbuda',
    ISOCode: 'XCD',
    Currency: 'East Caribbean dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Argentina',
    ISOCode: 'ARS',
    Currency: 'Argentine peso',
    Symbol: '$',
  },
  {
    CountryName: 'Armenia',
    ISOCode: 'AMD',
    Currency: 'Armenian dram',
    Symbol: '֏',
  },
  {
    CountryName: 'Australia',
    ISOCode: 'AUD',
    Currency: 'Australian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Austria',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Azerbaijan',
    ISOCode: 'AZN',
    Currency: 'Azerbaijani manat',
    Symbol: '₼',
  },
  {
    CountryName: 'Bahamas',
    ISOCode: 'BSD',
    Currency: 'Bahamian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Bahrain',
    ISOCode: 'BHD',
    Currency: 'Bahraini dinar',
    Symbol: '.د.ب',
  },
  {
    CountryName: 'Bangladesh',
    ISOCode: 'BDT',
    Currency: 'Bangladeshi taka',
    Symbol: '৳',
  },
  {
    CountryName: 'Barbados',
    ISOCode: 'BBD',
    Currency: 'Barbadian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Belarus',
    ISOCode: 'BYN',
    Currency: ' Belarusian ruble',
    Symbol: 'Br',
  },
  {
    CountryName: 'Belgium',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Belize',
    ISOCode: 'BZD',
    Currency: 'Belize dollar',
    Symbol: 'BZ$',
  },
  {
    CountryName: 'Benin',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Bhutan',
    ISOCode: 'BTN',
    Currency: 'Bhutanese ngultrum',
    Symbol: 'Nu.',
  },
  {
    CountryName: 'Bolivia',
    ISOCode: 'BOB',
    Currency: 'Bolivian boliviano',
    Symbol: '$b',
  },
  {
    CountryName: 'Bosnia and Herzegovina',
    ISOCode: 'BAM',
    Currency: 'Bosnia and Herzegovina convertible mark',
    Symbol: 'KM',
  },
  {
    CountryName: 'Botswana',
    ISOCode: 'BWP',
    Currency: 'Botswana pula',
    Symbol: 'P',
  },
  {
    CountryName: 'Brazil',
    ISOCode: 'BRL',
    Currency: 'Brazilian real',
    Symbol: 'R$',
  },
  {
    CountryName: 'Brunei',
    ISOCode: 'BND',
    Currency: 'Brunei dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Bulgaria',
    ISOCode: 'BGN',
    Currency: 'Bulgarian lev',
    Symbol: 'лв',
  },
  {
    CountryName: 'Burkina Faso',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Burundi',
    ISOCode: 'BIF',
    Currency: 'Burundian franc',
    Symbol: 'FBu',
  },
  {
    CountryName: 'Cambodia',
    ISOCode: 'KHR',
    Currency: 'Cambodian riel',
    Symbol: '៛',
  },
  {
    CountryName: 'Cameroon',
    ISOCode: 'XAF',
    Currency: 'Central African CFA franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Canada',
    ISOCode: 'CAD',
    Currency: 'Canadian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Cape Verde',
    ISOCode: 'CVE',
    Currency: 'Cape Verdean escudo',
    Symbol: '$',
  },
  {
    CountryName: 'Central African Republic',
    ISOCode: 'XAF',
    Currency: 'Central African CFA franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Chad',
    ISOCode: 'XAF',
    Currency: 'Central African CFA franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Chile',
    ISOCode: 'CLP',
    Currency: 'Chilean peso',
    Symbol: '$',
  },
  {
    CountryName: 'China',
    ISOCode: 'CNY',
    Currency: 'Chinese yuan',
    Symbol: '¥',
  },
  {
    CountryName: 'Colombia',
    ISOCode: 'COP',
    Currency: 'Colombian peso',
    Symbol: '$',
  },
  {
    CountryName: 'Comoros',
    ISOCode: 'KMF',
    Currency: 'Comorian franc',
    Symbol: 'CF',
  },
  {
    CountryName: 'Costa Rica',
    ISOCode: 'CRC',
    Currency: 'Costa Rican colón',
    Symbol: '₡',
  },
  {
    CountryName: 'Croatia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Cuba',
    ISOCode: 'CUP',
    Currency: 'Cuban peso',
    Symbol: '₱',
  },
  {
    CountryName: 'Cyprus',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Czech Republic',
    ISOCode: 'CZK',
    Currency: 'Czech koruna',
    Symbol: 'Kč',
  },
  {
    CountryName: 'Democratic Republic of Congo',
    ISOCode: 'CDF',
    Currency: 'Congolese franc',
    Symbol: 'FC',
  },
  {
    CountryName: 'Denmark',
    ISOCode: 'DKK',
    Currency: 'Danish krone',
    Symbol: 'kr',
  },
  {
    CountryName: 'Djibouti',
    ISOCode: 'DJF',
    Currency: 'Djiboutian franc',
    Symbol: 'Fdj',
  },
  {
    CountryName: 'Dominica',
    ISOCode: 'XCD',
    Currency: 'East Caribbean dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Dominican Republic',
    ISOCode: 'DOP',
    Currency: 'Dominican peso',
    Symbol: 'RD$',
  },
  {
    CountryName: 'East Timor',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Ecuador',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Egypt',
    ISOCode: 'EGP',
    Currency: 'Egyptian pound',
    Symbol: '£',
  },
  {
    CountryName: 'El Salvador',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Equatorial Guinea',
    ISOCode: 'XAF',
    Currency: 'Central African CFA franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Eritrea',
    ISOCode: 'ERN',
    Currency: 'Eritrean nakfa',
    Symbol: 'Nfk',
  },
  {
    CountryName: 'Estonia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Eswatini',
    ISOCode: 'SZL',
    Currency: 'Swazi lilangeni',
    Symbol: 'E',
  },
  {
    CountryName: 'Ethiopia',
    ISOCode: 'ETB',
    Currency: 'Ethiopian birr',
    Symbol: 'Br',
  },
  {
    CountryName: 'Fiji',
    ISOCode: 'FJD',
    Currency: 'Fijian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Finland',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'France',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Gabon',
    ISOCode: 'XAF',
    Currency: 'Central African CFA franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Gambia',
    ISOCode: 'GMD',
    Currency: 'Gambian dalasi',
    Symbol: 'D',
  },
  {
    CountryName: 'Georgia',
    ISOCode: 'GEL',
    Currency: 'Georgian lari',
    Symbol: '₾',
  },
  {
    CountryName: 'Germany',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Ghana',
    ISOCode: 'GHS',
    Currency: 'Ghanaian cedi',
    Symbol: 'GH₵',
  },
  {
    CountryName: 'Greece',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Grenada',
    ISOCode: 'XCD',
    Currency: 'East Caribbean dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Guatemala',
    ISOCode: 'GTQ',
    Currency: 'Guatemalan quetzal',
    Symbol: 'Q',
  },
  {
    CountryName: 'Guinea',
    ISOCode: 'GNF',
    Currency: 'Guinean franc',
    Symbol: 'FG',
  },
  {
    CountryName: 'Guinea-Bissau',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Guyana',
    ISOCode: 'GYD',
    Currency: 'Guyanese dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Haiti',
    ISOCode: 'HTG',
    Currency: 'Haitian gourde',
    Symbol: 'G',
  },
  {
    CountryName: 'Honduras',
    ISOCode: 'HNL',
    Currency: 'Honduran lempira',
    Symbol: 'L',
  },
  {
    CountryName: 'Hungary',
    ISOCode: 'HUF',
    Currency: 'Hungarian forint',
    Symbol: 'Ft',
  },
  {
    CountryName: 'Iceland',
    ISOCode: 'ISK',
    Currency: 'Icelandic króna',
    Symbol: 'kr',
  },
  {
    CountryName: 'India',
    ISOCode: 'INR',
    Currency: 'Indian rupee',
    Symbol: '₹',
  },
  {
    CountryName: 'Indonesia',
    ISOCode: 'IDR',
    Currency: 'Indonesian rupiah',
    Symbol: 'Rp',
  },
  {
    CountryName: 'Iran',
    ISOCode: 'IRR',
    Currency: 'Iranian rial',
    Symbol: '﷼',
  },
  {
    CountryName: 'Iraq',
    ISOCode: 'IQD',
    Currency: 'Iraqi dinar',
    Symbol: 'ع.د',
  },
  {
    CountryName: 'Ireland',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Israel',
    ISOCode: 'ILS',
    Currency: 'Israeli new shekel',
    Symbol: '₪',
  },
  {
    CountryName: 'Italy',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Ivory Coast',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Jamaica',
    ISOCode: 'JMD',
    Currency: 'Jamaican dollar',
    Symbol: 'J$',
  },
  {
    CountryName: 'Japan',
    ISOCode: 'JPY',
    Currency: 'Japanese yen',
    Symbol: '¥',
  },
  {
    CountryName: 'Jordan',
    ISOCode: 'JOD',
    Currency: 'Jordanian dinar',
    Symbol: 'JD',
  },
  {
    CountryName: 'Kazakhstan',
    ISOCode: 'KZT',
    Currency: 'Kazakhstani tenge',
    Symbol: 'лв',
  },
  {
    CountryName: 'Kenya',
    ISOCode: 'KES',
    Currency: 'Kenyan shilling',
    Symbol: 'KSh',
  },
  {
    CountryName: 'Kiribati',
    ISOCode: 'AUD',
    Currency: 'Australian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Korea, North',
    ISOCode: 'KPW',
    Currency: 'North Korean won',
    Symbol: '₩',
  },
  {
    CountryName: 'Korea, South',
    ISOCode: 'KRW',
    Currency: 'South Korean won',
    Symbol: '₩',
  },
  {
    CountryName: 'Kosovo',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Kuwait',
    ISOCode: 'KWD',
    Currency: 'Kuwaiti dinar',
    Symbol: 'KD',
  },
  {
    CountryName: 'Kyrgyzstan',
    ISOCode: 'KGS',
    Currency: 'Kyrgyzstani som',
    Symbol: 'лв',
  },
  {
    CountryName: 'Laos',
    ISOCode: 'LAK',
    Currency: 'Lao kip',
    Symbol: '₭',
  },
  {
    CountryName: 'Latvia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Lebanon',
    ISOCode: 'LBP',
    Currency: 'Lebanese pound',
    Symbol: '£',
  },
  {
    CountryName: 'Lesotho',
    ISOCode: 'LSL',
    Currency: 'Lesotho loti',
    Symbol: 'M',
  },
  {
    CountryName: 'Liberia',
    ISOCode: 'LRD',
    Currency: 'Liberian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Libya',
    ISOCode: 'LYD',
    Currency: 'Libyan dinar',
    Symbol: 'LD',
  },
  {
    CountryName: 'Liechtenstein',
    ISOCode: 'CHF',
    Currency: 'Swiss franc',
    Symbol: 'CHF',
  },
  {
    CountryName: 'Lithuania',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Luxembourg',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Madagascar',
    ISOCode: 'MGA',
    Currency: 'Malagasy ariary',
    Symbol: 'Ar',
  },
  {
    CountryName: 'Malawi',
    ISOCode: 'MWK',
    Currency: 'Malawian kwacha',
    Symbol: 'MK',
  },
  {
    CountryName: 'Malaysia',
    ISOCode: 'MYR',
    Currency: 'Malaysian ringgit',
    Symbol: 'RM',
  },
  {
    CountryName: 'Maldives',
    ISOCode: 'MVR',
    Currency: 'Maldivian rufiyaa',
    Symbol: 'Rf',
  },
  {
    CountryName: 'Mali',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Malta',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Marshall Islands',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Mauritania',
    ISOCode: 'MRO',
    Currency: 'Mauritanian ouguiya',
    Symbol: 'UM',
  },
  {
    CountryName: 'Mauritius',
    ISOCode: 'MUR',
    Currency: 'Mauritian rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Mexico',
    ISOCode: 'MXN',
    Currency: 'Mexican peso',
    Symbol: '$',
  },
  {
    CountryName: 'Micronesia',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Moldova',
    ISOCode: 'MDL',
    Currency: 'Moldovan leu',
    Symbol: 'lei',
  },
  {
    CountryName: 'Monaco',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Mongolia',
    ISOCode: 'MNT',
    Currency: 'Mongolian tögrög',
    Symbol: '₮',
  },
  {
    CountryName: 'Montenegro',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Morocco',
    ISOCode: 'MAD',
    Currency: 'Moroccan dirham',
    Symbol: 'MAD',
  },
  {
    CountryName: 'Mozambique',
    ISOCode: 'MZN',
    Currency: 'Mozambican metical',
    Symbol: 'MT',
  },
  {
    CountryName: 'Myanmar',
    ISOCode: 'MMK',
    Currency: 'Burmese kyat',
    Symbol: 'K',
  },
  {
    CountryName: 'Namibia',
    ISOCode: 'NAD',
    Currency: 'Namibian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Nauru',
    ISOCode: 'AUD',
    Currency: 'Australian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Nepal',
    ISOCode: 'NPR',
    Currency: 'Nepalese rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Netherlands',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'New Zealand',
    ISOCode: 'NZD',
    Currency: 'New Zealand dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Nicaragua',
    ISOCode: 'NIO',
    Currency: 'Nicaraguan córdoba',
    Symbol: 'C$',
  },
  {
    CountryName: 'Niger',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Nigeria',
    ISOCode: 'NGN',
    Currency: 'Nigerian naira',
    Symbol: '₦',
  },
  {
    CountryName: 'North Macedonia',
    ISOCode: 'MKD',
    Currency: 'Macedonian denar',
    Symbol: 'ден',
  },
  {
    CountryName: 'Norway',
    ISOCode: 'NOK',
    Currency: 'Norwegian krone',
    Symbol: 'kr',
  },
  {
    CountryName: 'Oman',
    ISOCode: 'OMR',
    Currency: 'Omani rial',
    Symbol: '﷼',
  },
  {
    CountryName: 'Pakistan',
    ISOCode: 'PKR',
    Currency: 'Pakistani rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Palau',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Palestine',
    ISOCode: 'ILS',
    Currency: 'Israeli new shekel',
    Symbol: '₪',
  },
  {
    CountryName: 'Panama',
    ISOCode: 'PAB',
    Currency: 'Panamanian balboa',
    Symbol: 'B/.',
  },
  {
    CountryName: 'Papua New Guinea',
    ISOCode: 'PGK',
    Currency: 'Papua New Guinean kina',
    Symbol: 'K',
  },
  {
    CountryName: 'Paraguay',
    ISOCode: 'PYG',
    Currency: 'Paraguayan guaraní',
    Symbol: 'Gs',
  },
  {
    CountryName: 'Peru',
    ISOCode: 'PEN',
    Currency: 'Peruvian sol',
    Symbol: 'S/.',
  },
  {
    CountryName: 'Philippines',
    ISOCode: 'PHP',
    Currency: 'Philippine peso',
    Symbol: '₱',
  },
  {
    CountryName: 'Poland',
    ISOCode: 'PLN',
    Currency: 'Polish zloty',
    Symbol: 'zł',
  },
  {
    CountryName: 'Portugal',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Qatar',
    ISOCode: 'QAR',
    Currency: 'Qatari riyal',
    Symbol: '﷼',
  },
  {
    CountryName: 'Republic of the Congo',
    ISOCode: 'XAF',
    Currency: 'Central African CFA franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Romania',
    ISOCode: 'RON',
    Currency: 'Romanian leu',
    Symbol: 'lei',
  },
  {
    CountryName: 'Russia',
    ISOCode: 'RUB',
    Currency: 'Russian ruble',
    Symbol: '₽',
  },
  {
    CountryName: 'Rwanda',
    ISOCode: 'RWF',
    Currency: 'Rwandan franc',
    Symbol: 'R₣',
  },
  {
    CountryName: 'Saint Kitts and Nevis',
    ISOCode: 'XCD',
    Currency: 'East Caribbean dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Saint Lucia',
    ISOCode: 'XCD',
    Currency: 'East Caribbean dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Saint Vincent and the Grenadines',
    ISOCode: 'XCD',
    Currency: 'East Caribbean dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Samoa',
    ISOCode: 'WST',
    Currency: 'Samoan tala',
    Symbol: 'WS$',
  },
  {
    CountryName: 'San Marino',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'São Tomé and Príncipe',
    ISOCode: 'STD',
    Currency: 'São Tomé and Príncipe dobra',
    Symbol: 'Db',
  },
  {
    CountryName: 'Saudi Arabia',
    ISOCode: 'SAR',
    Currency: 'Saudi riyal',
    Symbol: '﷼',
  },
  {
    CountryName: 'Senegal',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Serbia',
    ISOCode: 'RSD',
    Currency: 'Serbian dinar',
    Symbol: 'Дин.',
  },
  {
    CountryName: 'Seychelles',
    ISOCode: 'SCR',
    Currency: 'Seychellois rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Sierra Leone',
    ISOCode: 'SLL',
    Currency: 'Sierra Leonean leone',
    Symbol: 'Le',
  },
  {
    CountryName: 'Singapore',
    ISOCode: 'SGD',
    Currency: 'Singapore dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Slovakia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Slovenia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Solomon Islands',
    ISOCode: 'SBD',
    Currency: 'Solomon Islands dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Somalia',
    ISOCode: 'SOS',
    Currency: 'Somali shilling',
    Symbol: 'S',
  },
  {
    CountryName: 'South Africa',
    ISOCode: 'ZAR',
    Currency: 'South African rand',
    Symbol: 'R',
  },
  {
    CountryName: 'South Sudan',
    ISOCode: 'SSP',
    Currency: 'South Sudanese pound',
    Symbol: '£',
  },
  {
    CountryName: 'Spain',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Sri Lanka',
    ISOCode: 'LKR',
    Currency: 'Sri Lankan rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Sudan',
    ISOCode: 'SDG',
    Currency: 'Sudanese pound',
    Symbol: 'ج.س.',
  },
  {
    CountryName: 'Suriname',
    ISOCode: 'SRD',
    Currency: 'Surinamese dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Sweden',
    ISOCode: 'SEK',
    Currency: 'Swedish krona',
    Symbol: 'kr',
  },
  {
    CountryName: 'Switzerland',
    ISOCode: 'CHF',
    Currency: 'Swiss franc',
    Symbol: 'CHF',
  },
  {
    CountryName: 'Syria',
    ISOCode: 'SYP',
    Currency: 'Syrian pound',
    Symbol: '£',
  },
  {
    CountryName: 'Taiwan',
    ISOCode: 'TWD',
    Currency: 'New Taiwan dollar',
    Symbol: 'NT$',
  },
  {
    CountryName: 'Tajikistan',
    ISOCode: 'TJS',
    Currency: 'Tajikistani somoni',
    Symbol: 'SM',
  },
  {
    CountryName: 'Tanzania',
    ISOCode: 'TZS',
    Currency: 'Tanzanian shilling',
    Symbol: 'TSh',
  },
  {
    CountryName: 'Thailand',
    ISOCode: 'THB',
    Currency: 'Thai baht',
    Symbol: '฿',
  },
  {
    CountryName: 'Togo',
    ISOCode: 'XOF',
    Currency: 'West African CFA franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Tonga',
    ISOCode: 'TOP',
    Currency: "Tongan pa'anga",
    Symbol: 'T$',
  },
  {
    CountryName: 'Trinidad and Tobago',
    ISOCode: 'TTD',
    Currency: 'Trinidad and Tobago dollar',
    Symbol: 'TT$',
  },
  {
    CountryName: 'Tunisia',
    ISOCode: 'TND',
    Currency: 'Tunisian dinar',
    Symbol: 'د.ت',
  },
  {
    CountryName: 'Turkey',
    ISOCode: 'TRY',
    Currency: 'Turkish lira',
    Symbol: '₺',
  },
  {
    CountryName: 'Turkmenistan',
    ISOCode: 'TMT',
    Currency: 'Turkmenistan manat',
    Symbol: 'T',
  },
  {
    CountryName: 'Tuvalu',
    ISOCode: 'AUD',
    Currency: 'Australian dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Uganda',
    ISOCode: 'UGX',
    Currency: 'Ugandan shilling',
    Symbol: 'USh',
  },
  {
    CountryName: 'Ukraine',
    ISOCode: 'UAH',
    Currency: 'Ukrainian hryvnia',
    Symbol: '₴',
  },
  {
    CountryName: 'United Arab Emirates',
    ISOCode: 'AED',
    Currency: 'United Arab Emirates dirham',
    Symbol: 'د.إ',
  },
  {
    CountryName: 'United Kingdom',
    ISOCode: 'GBP',
    Currency: 'British pound',
    Symbol: '£',
  },
  {
    CountryName: 'United States',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Uruguay',
    ISOCode: 'UYU',
    Currency: 'Uruguayan peso',
    Symbol: '$U',
  },
  {
    CountryName: 'Uzbekistan',
    ISOCode: 'UZS',
    Currency: 'Uzbekistani som',
    Symbol: 'лв',
  },
  {
    CountryName: 'Vanuatu',
    ISOCode: 'VUV',
    Currency: 'Vanuatu vatu',
    Symbol: 'VT',
  },
  {
    CountryName: 'Vatican City',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Venezuela',
    ISOCode: 'VEF',
    Currency: 'Venezuelan bolívar',
    Symbol: 'Bs',
  },
  {
    CountryName: 'Vietnam',
    ISOCode: 'VND',
    Currency: 'Vietnamese dong',
    Symbol: '₫',
  },
  {
    CountryName: 'Yemen',
    ISOCode: 'YER',
    Currency: 'Yemeni rial',
    Symbol: '﷼',
  },
  {
    CountryName: 'Zambia',
    ISOCode: 'ZMW',
    Currency: 'Zambian kwacha',
    Symbol: 'ZK',
  },
  {
    CountryName: 'Zimbabwe',
    ISOCode: 'USD',
    Currency: 'United States dollar',
    Symbol: '$',
  },
];
