export const countryCurrencyList = [
  {
    CountryName: 'Euro Member Countries',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
    Presented: true,
  },
  {
    CountryName: 'United States',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
    Presented: true,
  },
  {
    CountryName: 'Central African CFA Franc BEAC',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc BEAC',
    Symbol: 'FCFA',
    Presented: true,
  },
  {
    CountryName: 'Afghanistan',
    ISOCode: 'AFN',
    Currency: 'Afghan Afghani',
    Symbol: '؋',
  },
  {
    CountryName: 'Albania',
    ISOCode: 'ALL',
    Currency: 'Albanian Lek',
    Symbol: 'Lek',
  },
  {
    CountryName: 'Algeria',
    ISOCode: 'DZD',
    Currency: 'Algerian Dinar',
    Symbol: 'دج',
  },
  {
    CountryName: 'Andorra',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Angola',
    ISOCode: 'AOA',
    Currency: 'Angolan Kwanza',
    Symbol: 'Kz',
  },
  {
    CountryName: 'Antigua and Barbuda',
    ISOCode: 'XCD',
    Currency: 'East Caribbean Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Argentina',
    ISOCode: 'ARS',
    Currency: 'Argentine Peso',
    Symbol: '$',
  },
  {
    CountryName: 'Armenia',
    ISOCode: 'AMD',
    Currency: 'Armenian Dram',
    Symbol: '֏',
  },
  {
    CountryName: 'Australia',
    ISOCode: 'AUD',
    Currency: 'Australian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Austria',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Azerbaijan',
    ISOCode: 'AZN',
    Currency: 'Azerbaijani Manat',
    Symbol: '₼',
  },
  {
    CountryName: 'Bahamas',
    ISOCode: 'BSD',
    Currency: 'Bahamian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Bahrain',
    ISOCode: 'BHD',
    Currency: 'Bahraini Dinar',
    Symbol: '.د.ب',
  },
  {
    CountryName: 'Bangladesh',
    ISOCode: 'BDT',
    Currency: 'Bangladeshi Taka',
    Symbol: '৳',
  },
  {
    CountryName: 'Barbados',
    ISOCode: 'BBD',
    Currency: 'Barbadian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Belarus',
    ISOCode: 'BYN',
    Currency: ' Belarusian Ruble',
    Symbol: 'Br',
  },
  {
    CountryName: 'Belgium',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Belize',
    ISOCode: 'BZD',
    Currency: 'Belize Dollar',
    Symbol: 'BZ$',
  },
  {
    CountryName: 'Benin',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Bhutan',
    ISOCode: 'BTN',
    Currency: 'Bhutanese Ngultrum',
    Symbol: 'Nu.',
  },
  {
    CountryName: 'Bolivia',
    ISOCode: 'BOB',
    Currency: 'Bolivian Boliviano',
    Symbol: '$b',
  },
  {
    CountryName: 'Bosnia and Herzegovina',
    ISOCode: 'BAM',
    Currency: 'Bosnia And Herzegovina Convertible Mark',
    Symbol: 'KM',
  },
  {
    CountryName: 'Botswana',
    ISOCode: 'BWP',
    Currency: 'Botswana Pula',
    Symbol: 'P',
  },
  {
    CountryName: 'Brazil',
    ISOCode: 'BRL',
    Currency: 'Brazilian Real',
    Symbol: 'R$',
  },
  {
    CountryName: 'Brunei',
    ISOCode: 'BND',
    Currency: 'Brunei Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Bulgaria',
    ISOCode: 'BGN',
    Currency: 'Bulgarian Lev',
    Symbol: 'лв',
  },
  {
    CountryName: 'Burkina Faso',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Burundi',
    ISOCode: 'BIF',
    Currency: 'Burundian Franc',
    Symbol: 'FBu',
  },
  {
    CountryName: 'Cambodia',
    ISOCode: 'KHR',
    Currency: 'Cambodian Riel',
    Symbol: '៛',
  },
  {
    CountryName: 'Cameroon',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Canada',
    ISOCode: 'CAD',
    Currency: 'Canadian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Cape Verde',
    ISOCode: 'CVE',
    Currency: 'Cape Verdean Escudo',
    Symbol: '$',
  },
  {
    CountryName: 'Central African Republic',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Chad',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Chile',
    ISOCode: 'CLP',
    Currency: 'Chilean Peso',
    Symbol: '$',
  },
  {
    CountryName: 'China',
    ISOCode: 'CNY',
    Currency: 'Chinese Yuan',
    Symbol: '¥',
  },
  {
    CountryName: 'Colombia',
    ISOCode: 'COP',
    Currency: 'Colombian Peso',
    Symbol: '$',
  },
  {
    CountryName: 'Comoros',
    ISOCode: 'KMF',
    Currency: 'Comorian Franc',
    Symbol: 'CF',
  },
  {
    CountryName: 'Costa Rica',
    ISOCode: 'CRC',
    Currency: 'Costa Rican Colón',
    Symbol: '₡',
  },
  {
    CountryName: 'Croatia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Cuba',
    ISOCode: 'CUP',
    Currency: 'Cuban Peso',
    Symbol: '₱',
  },
  {
    CountryName: 'Cyprus',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Czech Republic',
    ISOCode: 'CZK',
    Currency: 'Czech Koruna',
    Symbol: 'Kč',
  },
  {
    CountryName: 'Democratic Republic of Congo',
    ISOCode: 'CDF',
    Currency: 'Congolese Franc',
    Symbol: 'FC',
  },
  {
    CountryName: 'Denmark',
    ISOCode: 'DKK',
    Currency: 'Danish Krone',
    Symbol: 'kr',
  },
  {
    CountryName: 'Djibouti',
    ISOCode: 'DJF',
    Currency: 'Djiboutian Franc',
    Symbol: 'Fdj',
  },
  {
    CountryName: 'Dominica',
    ISOCode: 'XCD',
    Currency: 'East Caribbean Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Dominican Republic',
    ISOCode: 'DOP',
    Currency: 'Dominican Peso',
    Symbol: 'RD$',
  },
  {
    CountryName: 'East Timor',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Ecuador',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Egypt',
    ISOCode: 'EGP',
    Currency: 'Egyptian Pound',
    Symbol: '£',
  },
  {
    CountryName: 'El Salvador',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Equatorial Guinea',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Eritrea',
    ISOCode: 'ERN',
    Currency: 'Eritrean Nakfa',
    Symbol: 'Nfk',
  },
  {
    CountryName: 'Estonia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Eswatini',
    ISOCode: 'SZL',
    Currency: 'Swazi Lilangeni',
    Symbol: 'E',
  },
  {
    CountryName: 'Ethiopia',
    ISOCode: 'ETB',
    Currency: 'Ethiopian Birr',
    Symbol: 'Br',
  },
  {
    CountryName: 'Fiji',
    ISOCode: 'FJD',
    Currency: 'Fijian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Finland',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'France',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Gabon',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Gambia',
    ISOCode: 'GMD',
    Currency: 'Gambian Dalasi',
    Symbol: 'D',
  },
  {
    CountryName: 'Georgia',
    ISOCode: 'GEL',
    Currency: 'Georgian Lari',
    Symbol: '₾',
  },
  {
    CountryName: 'Germany',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Ghana',
    ISOCode: 'GHS',
    Currency: 'Ghanaian Cedi',
    Symbol: 'GH₵',
  },
  {
    CountryName: 'Greece',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Grenada',
    ISOCode: 'XCD',
    Currency: 'East Caribbean Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Guatemala',
    ISOCode: 'GTQ',
    Currency: 'Guatemalan Quetzal',
    Symbol: 'Q',
  },
  {
    CountryName: 'Guinea',
    ISOCode: 'GNF',
    Currency: 'Guinean Franc',
    Symbol: 'FG',
  },
  {
    CountryName: 'Guinea-Bissau',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Guyana',
    ISOCode: 'GYD',
    Currency: 'Guyanese Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Haiti',
    ISOCode: 'HTG',
    Currency: 'Haitian Gourde',
    Symbol: 'G',
  },
  {
    CountryName: 'Honduras',
    ISOCode: 'HNL',
    Currency: 'Honduran Lempira',
    Symbol: 'L',
  },
  {
    CountryName: 'Hungary',
    ISOCode: 'HUF',
    Currency: 'Hungarian Forint',
    Symbol: 'Ft',
  },
  {
    CountryName: 'Iceland',
    ISOCode: 'ISK',
    Currency: 'Icelandic Króna',
    Symbol: 'kr',
  },
  {
    CountryName: 'India',
    ISOCode: 'INR',
    Currency: 'Indian Rupee',
    Symbol: '₹',
  },
  {
    CountryName: 'Indonesia',
    ISOCode: 'IDR',
    Currency: 'Indonesian Rupiah',
    Symbol: 'Rp',
  },
  {
    CountryName: 'Iran',
    ISOCode: 'IRR',
    Currency: 'Iranian Rial',
    Symbol: '﷼',
  },
  {
    CountryName: 'Iraq',
    ISOCode: 'IQD',
    Currency: 'Iraqi Dinar',
    Symbol: 'ع.د',
  },
  {
    CountryName: 'Ireland',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Israel',
    ISOCode: 'ILS',
    Currency: 'Israeli New Shekel',
    Symbol: '₪',
  },
  {
    CountryName: 'Italy',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Ivory Coast',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Jamaica',
    ISOCode: 'JMD',
    Currency: 'Jamaican Dollar',
    Symbol: 'J$',
  },
  {
    CountryName: 'Japan',
    ISOCode: 'JPY',
    Currency: 'Japanese Yen',
    Symbol: '¥',
  },
  {
    CountryName: 'Jordan',
    ISOCode: 'JOD',
    Currency: 'Jordanian Dinar',
    Symbol: 'JD',
  },
  {
    CountryName: 'Kazakhstan',
    ISOCode: 'KZT',
    Currency: 'Kazakhstani Tenge',
    Symbol: 'лв',
  },
  {
    CountryName: 'Kenya',
    ISOCode: 'KES',
    Currency: 'Kenyan Shilling',
    Symbol: 'KSh',
  },
  {
    CountryName: 'Kiribati',
    ISOCode: 'AUD',
    Currency: 'Australian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Korea, North',
    ISOCode: 'KPW',
    Currency: 'North Korean Won',
    Symbol: '₩',
  },
  {
    CountryName: 'Korea, South',
    ISOCode: 'KRW',
    Currency: 'South Korean Won',
    Symbol: '₩',
  },
  {
    CountryName: 'Kosovo',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Kuwait',
    ISOCode: 'KWD',
    Currency: 'Kuwaiti Dinar',
    Symbol: 'KD',
  },
  {
    CountryName: 'Kyrgyzstan',
    ISOCode: 'KGS',
    Currency: 'Kyrgyzstani Som',
    Symbol: 'лв',
  },
  {
    CountryName: 'Laos',
    ISOCode: 'LAK',
    Currency: 'Lao Kip',
    Symbol: '₭',
  },
  {
    CountryName: 'Latvia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Lebanon',
    ISOCode: 'LBP',
    Currency: 'Lebanese Pound',
    Symbol: '£',
  },
  {
    CountryName: 'Lesotho',
    ISOCode: 'LSL',
    Currency: 'Lesotho Loti',
    Symbol: 'M',
  },
  {
    CountryName: 'Liberia',
    ISOCode: 'LRD',
    Currency: 'Liberian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Libya',
    ISOCode: 'LYD',
    Currency: 'Libyan Dinar',
    Symbol: 'LD',
  },
  {
    CountryName: 'Liechtenstein',
    ISOCode: 'CHF',
    Currency: 'Swiss Franc',
    Symbol: 'CHF',
  },
  {
    CountryName: 'Lithuania',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Luxembourg',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Madagascar',
    ISOCode: 'MGA',
    Currency: 'Malagasy Ariary',
    Symbol: 'Ar',
  },
  {
    CountryName: 'Malawi',
    ISOCode: 'MWK',
    Currency: 'Malawian Kwacha',
    Symbol: 'MK',
  },
  {
    CountryName: 'Malaysia',
    ISOCode: 'MYR',
    Currency: 'Malaysian Ringgit',
    Symbol: 'RM',
  },
  {
    CountryName: 'Maldives',
    ISOCode: 'MVR',
    Currency: 'Maldivian Rufiyaa',
    Symbol: 'Rf',
  },
  {
    CountryName: 'Mali',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Malta',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Marshall Islands',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Mauritania',
    ISOCode: 'MRO',
    Currency: 'Mauritanian Ouguiya',
    Symbol: 'UM',
  },
  {
    CountryName: 'Mauritius',
    ISOCode: 'MUR',
    Currency: 'Mauritian Rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Mexico',
    ISOCode: 'MXN',
    Currency: 'Mexican Peso',
    Symbol: '$',
  },
  {
    CountryName: 'Micronesia',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Moldova',
    ISOCode: 'MDL',
    Currency: 'Moldovan Leu',
    Symbol: 'lei',
  },
  {
    CountryName: 'Monaco',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Mongolia',
    ISOCode: 'MNT',
    Currency: 'Mongolian Tögrög',
    Symbol: '₮',
  },
  {
    CountryName: 'Montenegro',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Morocco',
    ISOCode: 'MAD',
    Currency: 'Moroccan Dirham',
    Symbol: 'MAD',
  },
  {
    CountryName: 'Mozambique',
    ISOCode: 'MZN',
    Currency: 'Mozambican Metical',
    Symbol: 'MT',
  },
  {
    CountryName: 'Myanmar',
    ISOCode: 'MMK',
    Currency: 'Burmese Kyat',
    Symbol: 'K',
  },
  {
    CountryName: 'Namibia',
    ISOCode: 'NAD',
    Currency: 'Namibian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Nauru',
    ISOCode: 'AUD',
    Currency: 'Australian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Nepal',
    ISOCode: 'NPR',
    Currency: 'Nepalese Rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Netherlands',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'New Zealand',
    ISOCode: 'NZD',
    Currency: 'New Zealand Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Nicaragua',
    ISOCode: 'NIO',
    Currency: 'Nicaraguan Córdoba',
    Symbol: 'C$',
  },
  {
    CountryName: 'Niger',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Nigeria',
    ISOCode: 'NGN',
    Currency: 'Nigerian Naira',
    Symbol: '₦',
  },
  {
    CountryName: 'North Macedonia',
    ISOCode: 'MKD',
    Currency: 'Macedonian Denar',
    Symbol: 'ден',
  },
  {
    CountryName: 'Norway',
    ISOCode: 'NOK',
    Currency: 'Norwegian Krone',
    Symbol: 'kr',
  },
  {
    CountryName: 'Oman',
    ISOCode: 'OMR',
    Currency: 'Omani Rial',
    Symbol: '﷼',
  },
  {
    CountryName: 'Pakistan',
    ISOCode: 'PKR',
    Currency: 'Pakistani Rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Palau',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Palestine',
    ISOCode: 'ILS',
    Currency: 'Israeli New Shekel',
    Symbol: '₪',
  },
  {
    CountryName: 'Panama',
    ISOCode: 'PAB',
    Currency: 'Panamanian Balboa',
    Symbol: 'B/.',
  },
  {
    CountryName: 'Papua New Guinea',
    ISOCode: 'PGK',
    Currency: 'Papua New Guinean Kina',
    Symbol: 'K',
  },
  {
    CountryName: 'Paraguay',
    ISOCode: 'PYG',
    Currency: 'Paraguayan Guaraní',
    Symbol: 'Gs',
  },
  {
    CountryName: 'Peru',
    ISOCode: 'PEN',
    Currency: 'Peruvian Sol',
    Symbol: 'S/.',
  },
  {
    CountryName: 'Philippines',
    ISOCode: 'PHP',
    Currency: 'Philippine Peso',
    Symbol: '₱',
  },
  {
    CountryName: 'Poland',
    ISOCode: 'PLN',
    Currency: 'Polish Zloty',
    Symbol: 'zł',
  },
  {
    CountryName: 'Portugal',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Qatar',
    ISOCode: 'QAR',
    Currency: 'Qatari Riyal',
    Symbol: '﷼',
  },
  {
    CountryName: 'Republic of the Congo',
    ISOCode: 'XAF',
    Currency: 'Central African Cfa Franc',
    Symbol: 'FCFA',
  },
  {
    CountryName: 'Romania',
    ISOCode: 'RON',
    Currency: 'Romanian Leu',
    Symbol: 'lei',
  },
  {
    CountryName: 'Russia',
    ISOCode: 'RUB',
    Currency: 'Russian Ruble',
    Symbol: '₽',
  },
  {
    CountryName: 'Rwanda',
    ISOCode: 'RWF',
    Currency: 'Rwandan Franc',
    Symbol: 'R₣',
  },
  {
    CountryName: 'Saint Kitts and Nevis',
    ISOCode: 'XCD',
    Currency: 'East Caribbean Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Saint Lucia',
    ISOCode: 'XCD',
    Currency: 'East Caribbean Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Saint Vincent and the Grenadines',
    ISOCode: 'XCD',
    Currency: 'East Caribbean Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Samoa',
    ISOCode: 'WST',
    Currency: 'Samoan Tala',
    Symbol: 'WS$',
  },
  {
    CountryName: 'San Marino',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'São Tomé and Príncipe',
    ISOCode: 'STD',
    Currency: 'São Tomé And Príncipe Dobra',
    Symbol: 'Db',
  },
  {
    CountryName: 'Saudi Arabia',
    ISOCode: 'SAR',
    Currency: 'Saudi Riyal',
    Symbol: '﷼',
  },
  {
    CountryName: 'Senegal',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Serbia',
    ISOCode: 'RSD',
    Currency: 'Serbian Dinar',
    Symbol: 'Дин.',
  },
  {
    CountryName: 'Seychelles',
    ISOCode: 'SCR',
    Currency: 'Seychellois Rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Sierra Leone',
    ISOCode: 'SLL',
    Currency: 'Sierra Leonean Leone',
    Symbol: 'Le',
  },
  {
    CountryName: 'Singapore',
    ISOCode: 'SGD',
    Currency: 'Singapore Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Slovakia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Slovenia',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Solomon Islands',
    ISOCode: 'SBD',
    Currency: 'Solomon Islands Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Somalia',
    ISOCode: 'SOS',
    Currency: 'Somali Shilling',
    Symbol: 'S',
  },
  {
    CountryName: 'South Africa',
    ISOCode: 'ZAR',
    Currency: 'South African Rand',
    Symbol: 'R',
  },
  {
    CountryName: 'South Sudan',
    ISOCode: 'SSP',
    Currency: 'South Sudanese Pound',
    Symbol: '£',
  },
  {
    CountryName: 'Spain',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Sri Lanka',
    ISOCode: 'LKR',
    Currency: 'Sri Lankan Rupee',
    Symbol: '₨',
  },
  {
    CountryName: 'Sudan',
    ISOCode: 'SDG',
    Currency: 'Sudanese Pound',
    Symbol: 'ج.س.',
  },
  {
    CountryName: 'Suriname',
    ISOCode: 'SRD',
    Currency: 'Surinamese Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Sweden',
    ISOCode: 'SEK',
    Currency: 'Swedish Krona',
    Symbol: 'kr',
  },
  {
    CountryName: 'Switzerland',
    ISOCode: 'CHF',
    Currency: 'Swiss Franc',
    Symbol: 'CHF',
  },
  {
    CountryName: 'Syria',
    ISOCode: 'SYP',
    Currency: 'Syrian Pound',
    Symbol: '£',
  },
  {
    CountryName: 'Taiwan',
    ISOCode: 'TWD',
    Currency: 'New Taiwan Dollar',
    Symbol: 'NT$',
  },
  {
    CountryName: 'Tajikistan',
    ISOCode: 'TJS',
    Currency: 'Tajikistani Somoni',
    Symbol: 'SM',
  },
  {
    CountryName: 'Tanzania',
    ISOCode: 'TZS',
    Currency: 'Tanzanian Shilling',
    Symbol: 'TSh',
  },
  {
    CountryName: 'Thailand',
    ISOCode: 'THB',
    Currency: 'Thai Baht',
    Symbol: '฿',
  },
  {
    CountryName: 'Togo',
    ISOCode: 'XOF',
    Currency: 'West African Cfa Franc',
    Symbol: 'CFA',
  },
  {
    CountryName: 'Tonga',
    ISOCode: 'TOP',
    Currency: "Tongan Pa'anga",
    Symbol: 'T$',
  },
  {
    CountryName: 'Trinidad and Tobago',
    ISOCode: 'TTD',
    Currency: 'Trinidad And Tobago Dollar',
    Symbol: 'TT$',
  },
  {
    CountryName: 'Tunisia',
    ISOCode: 'TND',
    Currency: 'Tunisian Dinar',
    Symbol: 'د.ت',
  },
  {
    CountryName: 'Turkey',
    ISOCode: 'TRY',
    Currency: 'Turkish Lira',
    Symbol: '₺',
  },
  {
    CountryName: 'Turkmenistan',
    ISOCode: 'TMT',
    Currency: 'Turkmenistan Manat',
    Symbol: 'T',
  },
  {
    CountryName: 'Tuvalu',
    ISOCode: 'AUD',
    Currency: 'Australian Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Uganda',
    ISOCode: 'UGX',
    Currency: 'Ugandan Shilling',
    Symbol: 'USh',
  },
  {
    CountryName: 'Ukraine',
    ISOCode: 'UAH',
    Currency: 'Ukrainian Hryvnia',
    Symbol: '₴',
  },
  {
    CountryName: 'United Arab Emirates',
    ISOCode: 'AED',
    Currency: 'United Arab Emirates Dirham',
    Symbol: 'د.إ',
  },
  {
    CountryName: 'United Kingdom',
    ISOCode: 'GBP',
    Currency: 'British Pound',
    Symbol: '£',
  },
  {
    CountryName: 'United States',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
  {
    CountryName: 'Uruguay',
    ISOCode: 'UYU',
    Currency: 'Uruguayan Peso',
    Symbol: '$U',
  },
  {
    CountryName: 'Uzbekistan',
    ISOCode: 'UZS',
    Currency: 'Uzbekistani Som',
    Symbol: 'лв',
  },
  {
    CountryName: 'Vanuatu',
    ISOCode: 'VUV',
    Currency: 'Vanuatu Vatu',
    Symbol: 'VT',
  },
  {
    CountryName: 'Vatican City',
    ISOCode: 'EUR',
    Currency: 'Euro',
    Symbol: '€',
  },
  {
    CountryName: 'Venezuela',
    ISOCode: 'VEF',
    Currency: 'Venezuelan Bolívar',
    Symbol: 'Bs',
  },
  {
    CountryName: 'Vietnam',
    ISOCode: 'VND',
    Currency: 'Vietnamese Dong',
    Symbol: '₫',
  },
  {
    CountryName: 'Yemen',
    ISOCode: 'YER',
    Currency: 'Yemeni Rial',
    Symbol: '﷼',
  },
  {
    CountryName: 'Zambia',
    ISOCode: 'ZMW',
    Currency: 'Zambian Kwacha',
    Symbol: 'ZK',
  },
  {
    CountryName: 'Zimbabwe',
    ISOCode: 'USD',
    Currency: 'United States Dollar',
    Symbol: '$',
  },
];
